In [1]:
import control
import numpy as np
import pandas as pd

from matplotlib import pyplot as plt

In [2]:
control.aom()
control.aod_h(frequency=100e6)
control.aod_v(frequency=100e6)

scope = control.MSOX6004A('172.22.22.30')
scope.holla()

'AGILENT TECHNOLOGIES,MSO-X 4054A,MY57310545,07.20.2017102615\n'

In [3]:
# max playback sample interval
dT = (2**16 - 1) * 4e-9

# frequency sweep duration
T = 1024 * dT

def interpolate(x, N=1024):
    i = np.linspace(0, 1, len(x))
    j = np.linspace(0, 1, N)
    
    return np.interp(j, i, x)

def measure(A):
    control.aod_h(frequency=100e6)
    control.aod_v(frequency=[80e6, 120e6], amplitude=interpolate(A), duration=T, nodwells=[False, True], interval=dT)
    
    df = scope.capture()
    df = df[(df.time > 0) & (df.time < T)]

    return interpolate(df.time), interpolate(df.voltage)

In [4]:
import os
import warnings

warnings.filterwarnings("ignore")

os.makedirs('optimization-data', exist_ok=True)

In [5]:
from scipy import optimize

A8 = np.ones(8)

U_target = .8

for i in range(len(A8)):
    U_error = 1e10
    
    for j in range(500):
        a = np.random.uniform(.2, 1.0)
    
        A_exp = A8.copy()
        A_exp[i] = a
        
        t, U = measure(A_exp)
        
        err = (interpolate(U, len(A_exp))[i] - U_target)**2
        
        if err < U_error:
            U_error = err
            A8[i] = a
            
            df = pd.DataFrame({'time': t, 'voltage': U, 'amplitude': interpolate(A8)})
            df.to_hdf('optimization-data/a8-800mV.h5', f'amplitude@{i}-iteration@{j}', complevel=9)
    
A8

KeyboardInterrupt: 

In [35]:
A16 = np.ones(16)

U_target = .8

for i in range(len(A16)):
    U_error = 1e10
    
    for j in range(500):
        a = np.random.uniform(.2, 1.0)
    
        A_exp = A16.copy()
        A_exp[i] = a
        
        t, U = measure(A_exp)
        
        err = (interpolate(U, len(A_exp))[i] - U_target)**2
        
        if err < U_error:
            U_error = err
            A16[i] = a
            
            df = pd.DataFrame({'time': t, 'voltage': U, 'amplitude': interpolate(A16)})
            df.to_hdf('optimization-data/a16-800mV.h5', f'amplitude@{i}-iteration@{j}', complevel=9)
    
A16

array([0.2834067 , 0.25995836, 0.26380977, 0.27070519, 0.2423294 ,
       0.21343067, 0.20305066, 0.20224217, 0.23056238, 0.25296592,
       0.26255874, 0.26111303, 0.27209064, 0.29279518, 0.33596962,
       0.26243773])

In [36]:
A32 = np.ones(32)

U_target = .8

for i in range(len(A32)):
    U_error = 1e10
    
    for j in range(500):
        a = np.random.uniform(.2, 1.0)
    
        A_exp = A32.copy()
        A_exp[i] = a
        
        t, U = measure(A_exp)
        
        err = (interpolate(U, len(A_exp))[i] - U_target)**2
        
        if err < U_error:
            U_error = err
            A32[i] = a
            
            df = pd.DataFrame({'time': t, 'voltage': U, 'amplitude': interpolate(A32)})
            df.to_hdf('optimization-data/a32-800mV.h5', f'amplitude@{i}-iteration@{j}', complevel=9)
    
A32

array([0.27653595, 0.27248424, 0.25926934, 0.26157993, 0.26391783,
       0.2719141 , 0.26655053, 0.26037754, 0.23926648, 0.23712531,
       0.21490539, 0.20525132, 0.20225253, 0.20151479, 0.20982988,
       0.20086376, 0.21948062, 0.24072505, 0.2473928 , 0.25722235,
       0.26268003, 0.25615449, 0.25974071, 0.26023923, 0.26300626,
       0.27390593, 0.28359031, 0.29284659, 0.31262858, 0.35244362,
       0.37145333, 0.2068266 ])

In [ ]:
A64 = np.ones(64)

U_target = .8

for i in range(len(A64)):
    U_error = 1e10
    
    for j in range(500):
        a = np.random.uniform(.2, 1.0)
    
        A_exp = A64.copy()
        A_exp[i] = a
        
        t, U = measure(A_exp)
        
        err = (interpolate(U, len(A_exp))[i] - U_target)**2
        
        if err < U_error:
            U_error = err
            A64[i] = a
            
            df = pd.DataFrame({'time': t, 'voltage': U, 'amplitude': interpolate(A64)})
            df.to_hdf('optimization-data/a64-800mV.h5', f'amplitude@{i}-iteration@{j}', complevel=9)
    
A64

In [ ]:
A128 = np.ones(128)

U_target = .8

for i in range(len(A128)):
    U_error = 1e10
    
    for j in range(500):
        a = np.random.uniform(.2, 1.0)
    
        A_exp = A128.copy()
        A_exp[i] = a
        
        t, U = measure(A_exp)
        
        err = (interpolate(U, len(A_exp))[i] - U_target)**2
        
        if err < U_error:
            U_error = err
            A128[i] = a
            
            df = pd.DataFrame({'time': t, 'voltage': U, 'amplitude': interpolate(A128)})
            df.to_hdf('optimization-data/a128-800mV.h5', f'amplitude@{i}-iteration@{j}', complevel=9)
    
A128

In [ ]:
A256 = np.ones(128)

U_target = .8

for i in range(len(A256)):
    U_error = 1e10
    
    for j in range(500):
        a = np.random.uniform(.2, 1.0)
    
        A_exp = A256.copy()
        A_exp[i] = a
        
        t, U = measure(A_exp)
        
        err = (interpolate(U, len(A_exp))[i] - U_target)**2
        
        if err < U_error:
            U_error = err
            A256[i] = a
            
            df = pd.DataFrame({'time': t, 'voltage': U, 'amplitude': interpolate(A256)})
            df.to_hdf('optimization-data/a256-800mV.h5', f'amplitude@{i}-iteration@{j}', complevel=9)
    
A256

In [ ]:
from scipy import optimize

A8 = np.ones(8)

U_target = 1.0

for i in range(len(A8)):
    U_error = 1e10
    
    for j in range(500):
        a = np.random.uniform(.2, 1.0)
    
        A_exp = A8.copy()
        A_exp[i] = a
        
        t, U = measure(A_exp)
        
        err = (interpolate(U, len(A_exp))[i] - U_target)**2
        
        if err < U_error:
            U_error = err
            A8[i] = a
            
            df = pd.DataFrame({'time': t, 'voltage': U, 'amplitude': interpolate(A8)})
            df.to_hdf('optimization-data/a8-1000mV.h5', f'amplitude@{i}-iteration@{j}', complevel=9)
    
A8

In [ ]:
A16 = np.ones(16)

U_target = 1.0

for i in range(len(A16)):
    U_error = 1e10
    
    for j in range(500):
        a = np.random.uniform(.2, 1.0)
    
        A_exp = A16.copy()
        A_exp[i] = a
        
        t, U = measure(A_exp)
        
        err = (interpolate(U, len(A_exp))[i] - U_target)**2
        
        if err < U_error:
            U_error = err
            A16[i] = a
            
            df = pd.DataFrame({'time': t, 'voltage': U, 'amplitude': interpolate(A16)})
            df.to_hdf('optimization-data/a16-1000mV.h5', f'amplitude@{i}-iteration@{j}', complevel=9)
    
A16

In [ ]:
A32 = np.ones(32)

U_target = 1.0

for i in range(len(A32)):
    U_error = 1e10
    
    for j in range(500):
        a = np.random.uniform(.2, 1.0)
    
        A_exp = A32.copy()
        A_exp[i] = a
        
        t, U = measure(A_exp)
        
        err = (interpolate(U, len(A_exp))[i] - U_target)**2
        
        if err < U_error:
            U_error = err
            A32[i] = a
            
            df = pd.DataFrame({'time': t, 'voltage': U, 'amplitude': interpolate(A32)})
            df.to_hdf('optimization-data/a32-1000mV.h5', f'amplitude@{i}-iteration@{j}', complevel=9)
    
A32

In [ ]:
A64 = np.ones(64)

U_target = 1.0

for i in range(len(A64)):
    U_error = 1e10
    
    for j in range(500):
        a = np.random.uniform(.2, 1.0)
    
        A_exp = A64.copy()
        A_exp[i] = a
        
        t, U = measure(A_exp)
        
        err = (interpolate(U, len(A_exp))[i] - U_target)**2
        
        if err < U_error:
            U_error = err
            A64[i] = a
            
            df = pd.DataFrame({'time': t, 'voltage': U, 'amplitude': interpolate(A64)})
            df.to_hdf('optimization-data/a64-1000mV.h5', f'amplitude@{i}-iteration@{j}', complevel=9)
    
A64

In [ ]:
A128 = np.ones(128)

U_target = 1.0

for i in range(len(A128)):
    U_error = 1e10
    
    for j in range(500):
        a = np.random.uniform(.2, 1.0)
    
        A_exp = A128.copy()
        A_exp[i] = a
        
        t, U = measure(A_exp)
        
        err = (interpolate(U, len(A_exp))[i] - U_target)**2
        
        if err < U_error:
            U_error = err
            A128[i] = a
            
            df = pd.DataFrame({'time': t, 'voltage': U, 'amplitude': interpolate(A128)})
            df.to_hdf('optimization-data/a128-1000mV.h5', f'amplitude@{i}-iteration@{j}', complevel=9)
    
A128

In [ ]:
A256 = np.ones(128)

U_target = 1.0

for i in range(len(A256)):
    U_error = 1e10
    
    for j in range(500):
        a = np.random.uniform(.2, 1.0)
    
        A_exp = A256.copy()
        A_exp[i] = a
        
        t, U = measure(A_exp)
        
        err = (interpolate(U, len(A_exp))[i] - U_target)**2
        
        if err < U_error:
            U_error = err
            A256[i] = a
            
            df = pd.DataFrame({'time': t, 'voltage': U, 'amplitude': interpolate(A256)})
            df.to_hdf('optimization-data/a256-1000mV.h5', f'amplitude@{i}-iteration@{j}', complevel=9)
    
A256

In [ ]:
from scipy import optimize

A8 = np.ones(8)

U_target = 1.2

for i in range(len(A8)):
    U_error = 1e10
    
    for j in range(500):
        a = np.random.uniform(.2, 1.0)
    
        A_exp = A8.copy()
        A_exp[i] = a
        
        t, U = measure(A_exp)
        
        err = (interpolate(U, len(A_exp))[i] - U_target)**2
        
        if err < U_error:
            U_error = err
            A8[i] = a
            
            df = pd.DataFrame({'time': t, 'voltage': U, 'amplitude': interpolate(A8)})
            df.to_hdf('optimization-data/a8-1200mV.h5', f'amplitude@{i}-iteration@{j}', complevel=9)
    
A8

In [ ]:
A16 = np.ones(16)

U_target = 1.2

for i in range(len(A16)):
    U_error = 1e10
    
    for j in range(500):
        a = np.random.uniform(.2, 1.0)
    
        A_exp = A16.copy()
        A_exp[i] = a
        
        t, U = measure(A_exp)
        
        err = (interpolate(U, len(A_exp))[i] - U_target)**2
        
        if err < U_error:
            U_error = err
            A16[i] = a
            
            df = pd.DataFrame({'time': t, 'voltage': U, 'amplitude': interpolate(A16)})
            df.to_hdf('optimization-data/a16-1200mV.h5', f'amplitude@{i}-iteration@{j}', complevel=9)
    
A16

In [ ]:
A32 = np.ones(32)

U_target = 1.2

for i in range(len(A32)):
    U_error = 1e10
    
    for j in range(500):
        a = np.random.uniform(.2, 1.0)
    
        A_exp = A32.copy()
        A_exp[i] = a
        
        t, U = measure(A_exp)
        
        err = (interpolate(U, len(A_exp))[i] - U_target)**2
        
        if err < U_error:
            U_error = err
            A32[i] = a
            
            df = pd.DataFrame({'time': t, 'voltage': U, 'amplitude': interpolate(A32)})
            df.to_hdf('optimization-data/a32-1200mV.h5', f'amplitude@{i}-iteration@{j}', complevel=9)
    
A32

In [ ]:
A64 = np.ones(64)

U_target = 1.2

for i in range(len(A64)):
    U_error = 1e10
    
    for j in range(500):
        a = np.random.uniform(.2, 1.0)
    
        A_exp = A64.copy()
        A_exp[i] = a
        
        t, U = measure(A_exp)
        
        err = (interpolate(U, len(A_exp))[i] - U_target)**2
        
        if err < U_error:
            U_error = err
            A64[i] = a
            
            df = pd.DataFrame({'time': t, 'voltage': U, 'amplitude': interpolate(A64)})
            df.to_hdf('optimization-data/a64-1200mV.h5', f'amplitude@{i}-iteration@{j}', complevel=9)
    
A64

In [ ]:
A128 = np.ones(128)

U_target = 1.2

for i in range(len(A128)):
    U_error = 1e10
    
    for j in range(500):
        a = np.random.uniform(.2, 1.0)
    
        A_exp = A128.copy()
        A_exp[i] = a
        
        t, U = measure(A_exp)
        
        err = (interpolate(U, len(A_exp))[i] - U_target)**2
        
        if err < U_error:
            U_error = err
            A128[i] = a
            
            df = pd.DataFrame({'time': t, 'voltage': U, 'amplitude': interpolate(A128)})
            df.to_hdf('optimization-data/a128-1200mV.h5', f'amplitude@{i}-iteration@{j}', complevel=9)
    
A128

In [5]:
A256 = np.ones(128)

U_target = 1.2

for i in range(len(A256)):
    U_error = 1e10
    
    for j in range(500):
        a = np.random.uniform(.2, 1.0)
    
        A_exp = A256.copy()
        A_exp[i] = a
        
        t, U = measure(A_exp)
        
        err = (interpolate(U, len(A_exp))[i] - U_target)**2
        
        if err < U_error:
            U_error = err
            A256[i] = a
            
            df = pd.DataFrame({'time': t, 'voltage': U, 'amplitude': interpolate(A256)})
            df.to_hdf('optimization-data/a256-1200mV.h5', f'amplitude@{i}-iteration@{j}', complevel=9)
    
A256

array([0.85793379, 0.66210333, 0.78141022, 0.47839508, 0.72440044,
       0.87156415, 0.81117096, 0.90748813, 0.56844061, 0.88873528,
       0.77838642, 0.73431377, 0.52432167, 0.76776316, 0.8603925 ,
       0.89352098, 0.74382667, 0.99170563, 0.39745634, 0.49969724,
       0.64578006, 0.88340012, 0.36142927, 0.32409479, 0.58888659,
       0.73158597, 0.92762187, 0.45776697, 0.99768978, 0.27419858,
       0.2200944 , 0.9255602 , 0.32318026, 0.52106494, 0.83329937,
       0.24195073, 0.74330827, 0.55878984, 0.44555816, 0.70911825,
       0.91281206, 0.51672693, 0.50821026, 0.97391189, 0.78620467,
       0.31385206, 0.20404541, 0.51452959, 0.24025981, 0.50162595,
       0.59011785, 0.67767897, 0.47969612, 0.86831589, 0.87097076,
       0.38517645, 0.73207081, 0.73900769, 0.58473544, 0.34047079,
       0.24662749, 0.348175  , 0.97581302, 0.43857062, 0.24810668,
       0.95951171, 0.79369759, 0.67614821, 0.32284171, 0.40670963,
       0.29913894, 0.94782175, 0.6246363 , 0.30033011, 0.90682