In [6]:
import control
import numpy as np
import pandas as pd

from matplotlib import pyplot as plt

In [16]:
control.aom()
control.aod_h(frequency=100e6)
control.aod_v(frequency=100e6)

scope = control.MSOX6004A('172.22.22.30')
scope.holla()

'AGILENT TECHNOLOGIES,MSO-X 4054A,MY57310545,07.20.2017102615\n'

In [8]:
# max playback sample interval
dT = (2**16 - 1) * 4e-9

# frequency sweep duration
T = 1024 * dT

def interpolate(x, N=1024):
    i = np.linspace(0, 1, len(x))
    j = np.linspace(0, 1, N)
    
    return np.interp(j, i, x)

def measure(A):
    control.aod_h(frequency=100e6)
    control.aod_v(frequency=[80e6, 120e6], amplitude=interpolate(A), duration=T, nodwells=[False, True], interval=dT)
    
    df = scope.capture()
    df = df[(df.time > 0) & (df.time < T)]

    return interpolate(df.time), interpolate(df.voltage)

In [9]:
import os
import warnings

warnings.filterwarnings("ignore")

os.makedirs('optimization-data', exist_ok=True)

In [37]:
from scipy import optimize

A8 = np.ones(8)

U_target = .8

for i in range(len(A8)):
    U_error = 1e10
    
    for j in range(500):
        a = np.random.uniform(.2, 1.0)
    
        A_exp = A8.copy()
        A_exp[i] = a
        
        t, U = measure(A_exp)
        
        err = (interpolate(U, len(A_exp))[i] - U_target)**2
        
        if err < U_error:
            U_error = err
            A8[i] = a
            
            df = pd.DataFrame({'time': t, 'voltage': U, 'amplitude': interpolate(A8)})
            df.to_hdf('optimization-data/800mV-8.h5', f'amplitude{i}/iteration{j}', complevel=9)
    
A8

array([0.29670128, 0.28758085, 0.26385799, 0.20216417, 0.25970242,
       0.30048077, 0.27085032, 0.50324864])

In [38]:
from scipy import optimize

A8 = np.ones(8)

U_target = 1.0

for i in range(len(A8)):
    U_error = 1e10
    
    for j in range(500):
        a = np.random.uniform(.2, 1.0)
    
        A_exp = A8.copy()
        A_exp[i] = a
        
        t, U = measure(A_exp)
        
        err = (interpolate(U, len(A_exp))[i] - U_target)**2
        
        if err < U_error:
            U_error = err
            A8[i] = a
            
            df = pd.DataFrame({'time': t, 'voltage': U, 'amplitude': interpolate(A8)})
            df.to_hdf('optimization-data/1000mV-8.h5', f'amplitude{i}/iteration@{j}', complevel=9)
    
A8

array([0.35088383, 0.3180698 , 0.3017809 , 0.21651422, 0.30682918,
       0.36652585, 0.26674604, 0.78912501])

In [39]:
from scipy import optimize

A8 = np.ones(8)

U_target = 1.2

for i in range(len(A8)):
    U_error = 1e10
    
    for j in range(500):
        a = np.random.uniform(.2, 1.0)
    
        A_exp = A8.copy()
        A_exp[i] = a
        
        t, U = measure(A_exp)
        
        err = (interpolate(U, len(A_exp))[i] - U_target)**2
        
        if err < U_error:
            U_error = err
            A8[i] = a
            
            df = pd.DataFrame({'time': t, 'voltage': U, 'amplitude': interpolate(A8)})
            df.to_hdf('optimization-data/1200mV-8.h5', f'amplitude{i}/iteration{j}', complevel=9)
    
A8

array([0.38732311, 0.35990127, 0.35070962, 0.22741702, 0.3409153 ,
       0.37122447, 0.36244967, 0.60676056])

In [40]:
A16 = np.ones(16)

U_target = .8

for i in range(len(A16)):
    U_error = 1e10
    
    for j in range(500):
        a = np.random.uniform(.2, 1.0)
    
        A_exp = A16.copy()
        A_exp[i] = a
        
        t, U = measure(A_exp)
        
        err = (interpolate(U, len(A_exp))[i] - U_target)**2
        
        if err < U_error:
            U_error = err
            A16[i] = a
            
            df = pd.DataFrame({'time': t, 'voltage': U, 'amplitude': interpolate(A16)})
            df.to_hdf('optimization-data/800mV-16.h5', f'amplitude{i}/iteration{j}', complevel=9)
    
A16

array([0.29821332, 0.28118328, 0.27810513, 0.30415035, 0.25995746,
       0.22496198, 0.2019899 , 0.37195609, 0.69640339, 0.29991318,
       0.51602801, 0.35580268, 0.5872501 , 0.70926122, 0.28538927,
       0.50281673])

In [41]:
A16 = np.ones(16)

U_target = 1.0

for i in range(len(A16)):
    U_error = 1e10
    
    for j in range(500):
        a = np.random.uniform(.2, 1.0)
    
        A_exp = A16.copy()
        A_exp[i] = a
        
        t, U = measure(A_exp)
        
        err = (interpolate(U, len(A_exp))[i] - U_target)**2
        
        if err < U_error:
            U_error = err
            A16[i] = a
            
            df = pd.DataFrame({'time': t, 'voltage': U, 'amplitude': interpolate(A16)})
            df.to_hdf('optimization-data/1000mV-16.h5', f'amplitude{i}/iteration{j}', complevel=9)
    
A16

array([0.3734661 , 0.31887009, 0.34634856, 0.34298713, 0.28251322,
       0.32471719, 0.21187564, 0.51006631, 0.37410409, 0.3697791 ,
       0.93900773, 0.20481952, 0.60319988, 0.31191768, 0.77386952,
       0.96476493])

In [42]:
A16 = np.ones(16)

U_target = 1.2

for i in range(len(A16)):
    U_error = 1e10
    
    for j in range(500):
        a = np.random.uniform(.2, 1.0)
    
        A_exp = A16.copy()
        A_exp[i] = a
        
        t, U = measure(A_exp)
        
        err = (interpolate(U, len(A_exp))[i] - U_target)**2
        
        if err < U_error:
            U_error = err
            A16[i] = a
            
            df = pd.DataFrame({'time': t, 'voltage': U, 'amplitude': interpolate(A16)})
            df.to_hdf('optimization-data/1200mV-16.h5', f'amplitude{i}/iteration{j}', complevel=9)
    
A16

array([0.4043573 , 0.38314906, 0.40070326, 0.35468426, 0.38904826,
       0.24630039, 0.5074548 , 0.46050686, 0.25794093, 0.9150914 ,
       0.48951574, 0.91543775, 0.6164894 , 0.51890191, 0.62098324,
       0.25227604])

In [43]:
A32 = np.ones(32)

U_target = .8

for i in range(len(A32)):
    U_error = 1e10
    
    for j in range(500):
        a = np.random.uniform(.2, 1.0)
    
        A_exp = A32.copy()
        A_exp[i] = a
        
        t, U = measure(A_exp)
        
        err = (interpolate(U, len(A_exp))[i] - U_target)**2
        
        if err < U_error:
            U_error = err
            A32[i] = a
            
            df = pd.DataFrame({'time': t, 'voltage': U, 'amplitude': interpolate(A32)})
            df.to_hdf('optimization-data/800mV-32.h5', f'amplitude{i}/iteration{j}', complevel=9)

A32

array([0.31973403, 0.31380073, 0.28942037, 0.31080267, 0.23541747,
       0.55469042, 0.8049138 , 0.41154155, 0.87439785, 0.85318316,
       0.38465727, 0.78672457, 0.96655727, 0.48781038, 0.2889445 ,
       0.85460412, 0.49107898, 0.94561104, 0.52535696, 0.63224473,
       0.64750295, 0.30627195, 0.53372698, 0.77224262, 0.3192937 ,
       0.60824305, 0.40325167, 0.7438034 , 0.39659478, 0.74302944,
       0.5675952 , 0.8219137 ])

In [44]:
A32 = np.ones(32)

U_target = 1.0

for i in range(len(A32)):
    U_error = 1e10
    
    for j in range(500):
        a = np.random.uniform(.2, 1.0)
    
        A_exp = A32.copy()
        A_exp[i] = a
        
        t, U = measure(A_exp)
        
        err = (interpolate(U, len(A_exp))[i] - U_target)**2
        
        if err < U_error:
            U_error = err
            A32[i] = a
            
            df = pd.DataFrame({'time': t, 'voltage': U, 'amplitude': interpolate(A32)})
            df.to_hdf('optimization-data/1000mV-32.h5', f'amplitude{i}/iteration{j}', complevel=9)
    
A32

array([0.37561057, 0.33846043, 0.40475727, 0.21271836, 0.64888077,
       0.76344553, 0.66989913, 0.38845293, 0.92354614, 0.4984014 ,
       0.88815152, 0.41540989, 0.5770842 , 0.76627659, 0.34851747,
       0.49768199, 0.22676328, 0.52661441, 0.99024358, 0.86659564,
       0.20045802, 0.62855104, 0.4983925 , 0.48062906, 0.58769912,
       0.59189398, 0.5077311 , 0.20013463, 0.90279761, 0.22483886,
       0.51282767, 0.38286983])

In [45]:
A32 = np.ones(32)

U_target = 1.2

for i in range(len(A32)):
    U_error = 1e10
    
    for j in range(500):
        a = np.random.uniform(.2, 1.0)
    
        A_exp = A32.copy()
        A_exp[i] = a
        
        t, U = measure(A_exp)
        
        err = (interpolate(U, len(A_exp))[i] - U_target)**2
        
        if err < U_error:
            U_error = err
            A32[i] = a
            
            df = pd.DataFrame({'time': t, 'voltage': U, 'amplitude': interpolate(A32)})
            df.to_hdf('optimization-data/1200mV-32.h5', f'amplitude{i}/iteration{j}', complevel=9)
    
A32

array([0.41461954, 0.38743545, 0.34741169, 0.4279459 , 0.24551701,
       0.77370544, 0.91543592, 0.25519002, 0.40399137, 0.50182735,
       0.29055073, 0.44756718, 0.51107556, 0.62025876, 0.81063077,
       0.42514163, 0.92854062, 0.2639656 , 0.39256183, 0.64163182,
       0.31914435, 0.91026124, 0.69576848, 0.5090474 , 0.36707306,
       0.84387496, 0.66650967, 0.93370557, 0.29476856, 0.41532753,
       0.45875071, 0.31072442])

<Response [204]>